### ISSUE TITLE
KnockoutJS Support

### ISSUE THREAD

**Issue by reddyBell** [bridgedotnet/Frameworks#58]
Hello !

Have the Knockout metadata from the Satarelle project been ported ? I can't find the source code for this : https://www.nuget.org/packages/Saltarelle.Knockout/

Any pointer would be appreciated, many thanks

**Comment by geoffreymcgill** [comment]
Hi @reddyBell,

We haven't ported the Knockout project from Saltarelle, because we're working on a much more comprehensive solution. Unfortunately, that new project is not ready for release, and the timelines are still a little unknown, but we are doing our best to get it released as soon as possible. 

At this point, if **Bridge.Knockout** is required, the original [SaltarelleKnockout](https://github.com/Saltarelle/SaltarelleKnockout) project would have to be upgraded to Bridge. You would probably only have to focus on the projects [/Knockout](https://github.com/Saltarelle/SaltarelleKnockout/tree/develop/Knockout) folder.

The [Upgrade from Saltarelle](https://github.com/bridgedotnet/Bridge/wiki/Upgrade-from-Saltarelle) wiki doc can help get things started. Please feel free to make revisions to the wiki document.

Hope this helps.
